config/routes.rb
Urlsplease::Application.routes.draw do |map|
  
  resources :tags
  
  match 'requests/tagged(/:search_string)', 
    :to => 'requests#tag_search',
    :as => 'requests_tagged'
  # match 'requests/tagged', :to => 'requests#tag_search'          # For POST
  
  resources :resources   
  
  resources :requests
  
  devise_for :users, :path => 'accounts'
  
  resources :users do
    resources :resources
    resources :requests do       
      resources :resources
    end
    resources :tag_subscriptions
  end
  
  resources :profiles
  
  get "welcome/index"
  get "welcome/purpose"
  get "welcome/todo"
  get "welcome/releasenotes"
  
  root :to => "welcome#index"
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_filter :authenticate_user!
  
  before_filter :get_user_by_nickname_from_id
  
  def show
    @tags = @user.tags
    @recommended_requests = Request.find_by_tags(@tags)
    @responses = @user.responses
  end

  def edit
  end

  def update
  end


  private
  
  def get_user_by_nickname_from_id
    @user = User.where(:nickname => params[:id]).first
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>

app/views/profiles/show.html.erb
<% content_for :title do "Start page for #{user @user}" end %>

<h2>Your start page</h2>

<h3>Recent responses to your requests:</h3>

<% @responses.each do |response| %>
<p><%= link_to response.url, response.url %><br />
  Posted <%= dateandtime(response) %> by <%= user response %><br />
  In response to: 
  <%= link_to response.request.excerpt, user_request_path(@user, response.request) %>
<% end %>

<h3>Suggested requests</h3>
<% @recommended_requests.each do |request| %>
<p><%= link_to request.excerpt, user_request_path(request.user, request) %><br />
  Tagged: <%=linked_tags request.tags %>
  <% if request.resources.size > 0 -%>
    <br />
    <%= request.resources.size %> responses as of 
    <%= dateandtime(request.resources.first) %>
  <% end -%></p>
<% end %>

<h3>Tags you follow</h3>

<p><%= linked_tags @tags %>
<br />
<%= link_to "Add or remove tags", user_tag_subscriptions_path(@user) %></p>

<h3>Your personal information</h3>
<p><b>Nickname</b>: <%= @user.nickname %><br />
  <b>Member since</b>: <%= dateonly(@user) %></p>

<h3>Other things you might want to do</h3>
<p><%= link_to "View all your requests.", user_requests_path(@user) %></p>
<p><%= link_to "View all the resources you've posted.", user_resources_path(@user) %></p>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>