config/routes.rb
Urlsplease::Application.routes.draw do |map|
  
  resources :tags
  
  match 'requests/tagged(/:search_string)', 
    :to => 'requests#tag_search',
    :as => 'requests_tagged'
  # match 'requests/tagged', :to => 'requests#tag_search'          # For POST
  
  resources :resources   
  
  resources :requests
  
  devise_for :users, :path => 'accounts'
  
  resources :users do
    resources :resources
    resources :requests do       
      resources :resources
    end
    resources :tag_subscriptions
  end
  
  resources :profiles
  
  get "welcome/index"
  get "welcome/purpose"
  get "welcome/todo"
  get "welcome/releasenotes"
  
  root :to => "welcome#index"
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% content_for :title do "Home" end %>

<h2>Welcome to URLs Please</h2>

<% unless user_signed_in? -%>
<h3>Sign up</h3>
<p>It's very simple: just <%= link_to "gimme a nickname and valid email address", new_user_registration_path %> I won't share or use to send you spam. That's it for the personal information. No market segmentation necessary: we're all friends here.</p>
<% end %>

<h3>Post a request</h3>
<p>Wish someone had written a good blog post or made a screencast or podcast about a topic dear to your heart? 
<%= user_signed_in? ? 
  link_to("Just ask for it", new_user_request_path(current_user)) : 
  "Just ask for it" %>. This is your opportunity to ask the world to make it so.</p> 

<h3>Or, prepare and submit a response</h3>
<p>Are you a blogger or other content creator? Do you fancy yourself an expert on some topic? Looking for something to write or record about? <%= link_to "Find ideas here", requests_path %> and make something you know someone wants. Then post the URL. You own your content and share the link.</p>

<h3>Is this it?</h3>
<p>I know this is not a sophisticated web page. How do I plan to monetize this? What's my plan for the spam bots that will arrive any moment? Why don't I even have a 1995-era FAQ?<p>
  
<p>I'm working on all of this, possibly even as you're reading this. I have a <%= link_to "to-do list", welcome_todo_path %>, but the important thing is to launch and find some (free) customers to help me find out what URLs Please ought to be. This is a personal project. I'm going to keep it free, and ad-free unless (the hubris!) I need to pay for increased traffic.</p>
  
<h3>Want the whole story?</h3>
<p>I'm good at writing in the long form, so you should read my <%= link_to "statement of purpose", welcome_purpose_path %> if you're interested in the details of my crackpot idea.</p>

app/views/welcome/purpose.html.erb
<% content_for :title do "Windy statement of purpose" end %>

<h2>Hello, hello, what's all this then?</h2>

<p>URLs Please is an experiment in collaborative community content creation. It's a (free) marketplace for ideas for blog posts, articles, videos, screencasts, etc. It's also a personal journey into some application development topics, like scalability and data science, that I want to get some hands-on experience tackling.</p>

<h3>What do you want to know?</h3>

<p>I want a place for content creation supply to meet content demand, but I want the exchange to happen between individuals, outside the control of content aggregators.
  I was inspired by the <%= link_to "skribit", "http://skribit.com/" %> widget on <%= link_to "Yehuda Katz's website", "http://yehudakatz.com/" %>. It lets visitors suggest topics for a blogger to write about. For Yehuda, who is an expert on Ruby, JavaScript, and web frameworks, the suggested topics are technical. What if this capacity were available at a higher level? The idea for a marketplace or clearinghouse for non-commercial content creation is compelling. 

<h3>Content, community, collaboration</h3>

<p>The World Wide Web was intended to be as much about production as consumption. We almost take it for granted that the walled gardens of content aggregators truly make this the best possible world. I'm inspired by people like J Chris Anderson, who argue <%= link_to "things could be different", "http://jchrisa.net/drl/_design/sofa/_show/post/Imagine-There-s-No-YouTube"%>. I want to champion an older model in which content creators author and host their own works and share them using the simple elegance of the link to a URL.</p>

<p>I am not trying to recreate the search engine or sites like <%= link_to "Stack Overflow","http://stackoverflow.com/" %>. I want my effort to complement, not replace or co-opt, the healthy functioning of our World Wide Web. I'm not link-farming or click-hoarding or whatever. Once the content is out there, it belongs to the community of producers who made it. URLs Please just catalyzes and records.</p>

<h3>An odyssey into open source software</h3>
<p>I don't just want URLs Please to <em>use</em> open source software. I want it to <em>contribute</em> to OSS. I plan to extract plugins, gems, libraries, and sub-projects from my efforts and put them up on github for the world to use and fork.</p>

<h3>Quality and standards</h3>
<p>As soon as I have any mechanisms for distinguishing the contents of the resources submitted, I plan not only to penalize and remove spammy or off-topic offerings, but also to give preference to those that follow good coding and accessibility standards. We all need to do our best to make the web easier for human beings to use.</p>

app/views/welcome/releasenotes.html.erb
<% content_for :title do "Release notes" end %>

<% content_for :css do %>
ul.retired li {
  text-decoration: line-through;
}
<% end %>

<h2>Release Notes</h2>

<h3>Version 0.1</h3>
July 28, 2010

<ul>
  <li>Basic Navigation, Homepage, etc.</li>
  <li>Nested Resources in Requests, incl. listing and post link on Request page</li>
  <li>Tags for request characterization</li>
  <li>Devise for authentication</li>
  <li>Point URL to heroku app. Zerigo, custom domain.</li>
  <li>Google apps for email.</li>
  <li>Add urlsplease github account.</li>
  <li>Validate resources as URLs</li>
  <li>Excerpt requests for listing display (100 characters)</li>
  <li>Pitchier homepage: in search of (free) customers</li>
  <li>Make Tag use contents instead of numerical ID in RESTful paths</li>
  <li>Make User use contents instead of numerical ID in RESTful paths</li>
  <li>Search by tags.</li>
  <li>Separate tags by whitespace, stop singularizing</li>
  <li>User tag "subscriptions"</li>
  <li>User profiles / views with tags to watch, personal requests and responses.</li>
  <li>Limit controllers' access to authenticated users.</li>
  <li>reCAPTCHA for account creation.</li>
</ul>

app/views/welcome/todo.html.erb
<% content_for :title do "To-do items" end %>

<% content_for :css do %>
ul.retired li {
  text-decoration: line-through;
}
<% end %>

<p><b>Current Version: 0.1</b> 
  (<%= link_to "release notes", welcome_releasenotes_path %>)<br />
  July 28, 2010</p>

<h2>To do</h2>

<h3>Immediate goal: Open up traffic</h3>
<ul>
  <li>Flog: blog posts, twitter, personal emails.</li>
  <li>Google analytics</li>
</ul>

<h3>Immediate goal: Better testing</h3>
<ul>
  <li>Replace laborious instance creation in specs with fixture use</li>
  <li>Add integration tests</li>
</ul>

<h3>Minor improvements</h3>
<ul>
  <li>Reverse chronological order for many listings</li>
  <li>Recommended requests should not include your own</li>
</ul>

<h3>For version 0.2:</h3>
<ul>
  <li>Incrementally better interface.</li>
  <li>Some basic branding.</li>
  <li>Recommending requests by tag should be cumulative: more tag matches, higher position</li>
  <li>Eat my own mustache dog food.</li>
</ul>

<h3>For future versions:</h3>
<ul>
  <li>Use OpenID only</li>
  <li>Do performance tests work in Rails 3?</li>
  <li>Add basic cache and sweep.</li>
  <li>Show a preview of request excerpt as a user types.</li>
  <li>Suggest tags as user types</li>
  
  <li>Token to place in blog post to confirm authorship.</li>
  <li>Tags for resource, user expertise characterization</li>
  <li>Suggest tags for user based on existing subscriptions</li>
  <li>Ratings by click, user reputation</li>
  <li>Applaud and complain options</li>
  <li>Summary gathering from resources (scraping)</li>
  <li>Bayesian analysis for spam, link farms</li>
  <li>CanSpam, Phishing registry filters on resources</li>
  <li>Search by request contents</li>
  <li>Rate well-formatted and accessible HTML resources higher</li>
  <li>Anti-robot measures on posting resources and responses, if necessary</li>
  <li>Gravatars for users</li>
</ul>
<h3>A gleam in my eye</h3>
<ul>
  <li>Allow users to tag others users (reputation)
  <li>Gather communities by who has responded to whom, who reads whose requests and resources</li>
  <li>Rate high google score resources higher</li>
  <li>Admin review and/or review requests by user referees (by tag)</li>
  <li>Social network integration: Tweet or FB status update for request, (hashtags too).<br />
      Post popular requests, responses to content aggravators.</li>
</ul>

<h3>Recently retired:<h3>
<ul>
  <li>Extract security-sensitive configuration info from repository code<li>
  <li>Open-source code<li>
  <li>Since password salt has changed, make email password update mechanism work (Sendgrid)</li>
  <li>Test at high numbers of records.</li>
</ul>