config/routes.rb
Urlsplease::Application.routes.draw do |map|
  
  resources :tags
  
  match 'requests/tagged(/:search_string)', 
    :to => 'requests#tag_search',
    :as => 'requests_tagged'
  # match 'requests/tagged', :to => 'requests#tag_search'          # For POST
  
  resources :resources   
  
  resources :requests
  
  devise_for :users, :path => 'accounts'
  
  resources :users do
    resources :resources
    resources :requests do       
      resources :resources
    end
    resources :tag_subscriptions
  end
  
  resources :profiles
  
  get "welcome/index"
  get "welcome/purpose"
  get "welcome/todo"
  get "welcome/releasenotes"
  
  root :to => "welcome#index"
  
end

app/models/request.rb
class Request < ActiveRecord::Base
  
  include Taggable
  
  belongs_to :user
  has_many :resources
  
  validates :user, :presence => true
  validates :requirements, :presence => true
  
  # user is not accessible to mass assign: must be set explicitly
  attr_accessible :requirements
  
  scope :recent, order("requests.created_at DESC")
  
  def self.by_response_count
    Request.find_by_sql("SELECT requests.id, requests.requirements, 
      requests.user_id, requests.created_at, requests.updated_at, 
      users.nickname AS username,
      COALESCE(resources_external.count_id,0) AS response_count 
      FROM requests LEFT OUTER JOIN (SELECT resources.request_id,
      COUNT(resources.id) AS count_id FROM resources GROUP BY resources.request_id)
      resources_external ON requests.id = resources_external.request_id
      LEFT OUTER JOIN users ON requests.user_id = users.id
      ORDER BY response_count DESC
      LIMIT 100")
  end
  
  def excerpt(chars=100)
    return requirements unless requirements.length > chars
    pos = chars - 3
    while !(requirements[pos,1] =~ /\W+/) && pos > 0
      pos -= 1
    end
    requirements[0,pos] + "..."
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  verify :method => :delete, :only => [ :destroy ], 
       :render => {:text => '405 HTTP DELETE required', :status => 405}, 
       :add_headers => {'Allow' => 'DELETE'}
  
  before_filter :authenticate_user!
  before_filter :get_user_by_userid,     :only   => [:index]
  before_filter :require_user_by_userid, :except => [:index, :tag_search]
  

  def index
    if @user
      @requests = @user.requests.sort {|a,b| b.resources.size <=> a.resources.size }
    else
      @requests = Request.by_response_count
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @requests }
    end
  end


  def show
    @request   = @user.requests.find(params[:id])
    @resources = @request.resources
    @resource  = @resources.build() # For quick-response form
    @tags      = @request.tags

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @request }
    end
  end


  def new
    return render_404 unless current_user == @user
    @request = @user.requests.build()

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @request }
    end
  end


  def edit
    return render_404 unless current_user == @user
    @request = @user.requests.find(params[:id])
  end


  def create
    return render_404 unless current_user == @user
    @request = @user.requests.build(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to(user_request_path(@user,@request), :notice => 'Request was successfully created.') }
        format.xml  { render :xml => @request, :status => :created, :location => @request }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end


  def update
    return render_404 unless current_user == @user
    @request = @user.requests.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to(user_request_path(@user,@request), :notice => 'Request was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end


  def destroy
    render(:status => "501") # destroy not permitted
  end
  
  
  def tag_search
    @search_tags = Tag.split(params[:search_string])
    @requests = Request.find_by_tag_contents(@search_tags)
  end
  
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/destroy.html.erb
<% content_for :title do "Nope" end %>

<h2>Deletion is not permitted.</h2>

app/views/requests/edit.html.erb
<% content_for :title do "Edit request" end %>

<h2>Edit your request</h2>

<%= form_for(@request, :url => user_request_path(@user, @request)) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requirements %><br />
    <%= f.text_area :requirements, :cols=>80, :rows=>10 %>
  </div>
  
<% unless @request.taggings.blank? %>
  <p><b>Existing tags</b>: <%= @request.tags.collect(&:contents).join(', ') %></p>
<% end %>
  
  <div class="field">
    <%= f.label :new_tags %> (separated by commas)<br />
    <%= f.text_area :new_tags, :cols=>80, :rows=>4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<% content_for :title do "Requests" end %>

<h2>Listing requests</h2>

<table>

<% @requests.each do |request| %>
<p><%= link_to request.excerpt, user_request_path(request.username, request) %>
    by <%= link_to request.username, user_path(request.username) %><br />
    <%= "#{request.response_count} responses" if request.response_count.to_i > 0 %> </p>

<% end %>

<br />

<h2>Search by tag</h2>

<%= form_tag requests_tagged_path %>

<p>
  <%= label_tag 'search_string', 'Tags to search for' %> (separate with spaces or commas)<br>
  <%= text_field_tag 'search_string', '', :size => 30 %>
</p>
<%= submit_tag("Search") %>
</form>

<br />
<br />


<%= link_to 'New Request', new_user_request_path(current_user) %>

app/views/requests/new.html.erb
<% content_for :title do "New request" end %>

<h2>New request</h2>

<p>What would you like to know?</p>

<%= form_for(@request, :url => user_requests_path(@user)) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requirements %><br />
    <%= f.text_area :requirements, :cols=>80, :rows=>10 %>
  </div>
  
  <div class="field">
    <%= f.label :new_tags %> (separate with spaces or commas)<br />
    <%= f.text_field :new_tags, :size => 88 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<% content_for :title do "Request by #{user @request}" end %>

<h2>Request</h2>
<p>
  <b>Requirements:</b>
  <%= @request.requirements %>
</p>

<p>
  <b>Posted by:</b>
  <%= link_to user(@request), @request.user %>
</p>

<p><b>Tags:</b></p>

<p><%= linked_tags @request.tags %></p>

<p><b>Resources posted in response:</b></p>

<ul>
<% @resources.each do |r| %>
<% unless r.new_record? %>
  <li><%= link_to r.url, r.url %> by <%= link_to user(r), r.user %></li>
  <% end %>
<% end %>
</ul>

<p><b>Post a resource:</b></p>
<%= form_for @resource, :url => user_request_resources_path(current_user, @request) do |r| %>
  <%= r.text_area :url, :cols => 80, :rows => 3 %>
  <br clear="all" />
  <%= submit_tag 'Create' %>
<% end %>
<%= link_to 'Back', requests_path %>

app/views/requests/tag_search.html.erb
<% content_for :title do "Requests" end %>

<h2>Requests matching tags</h2>

<p><b>Searched for:</b> <%= @search_tags.join(', ') %></p>

<table>

<% @requests.each do |request| %>
<p><%= link_to request.excerpt, user_request_path(request.user, request) %>
    by: <%= user request %><br />
    tags: <%= linked_tags request.tags %><br />
    <%= "#{request.resources.size} responses" if request.resources.size > 0 %> </p>

<% end %>

<br />

<h2>Search again</h2>

<%= form_tag requests_tagged_path %>

<p>
  <%= label_tag 'search_string', 'Tags to search for' %> (separate with commas)<br>
  <%= text_field_tag 'search_string' %>
</p>
<%= submit_tag("Search") %>
</form>

<br />
<br />

<%= link_to 'Back', requests_path %> |
<%= link_to 'New Request', new_user_request_path(current_user) %>