config/routes.rb
Urlsplease::Application.routes.draw do |map|
  
  resources :tags
  
  match 'requests/tagged(/:search_string)', 
    :to => 'requests#tag_search',
    :as => 'requests_tagged'
  # match 'requests/tagged', :to => 'requests#tag_search'          # For POST
  
  resources :resources   
  
  resources :requests
  
  devise_for :users, :path => 'accounts'
  
  resources :users do
    resources :resources
    resources :requests do       
      resources :resources
    end
    resources :tag_subscriptions
  end
  
  resources :profiles
  
  get "welcome/index"
  get "welcome/purpose"
  get "welcome/todo"
  get "welcome/releasenotes"
  
  root :to => "welcome#index"
  
end

app/views/resources/edit.html.erb
<% content_for :title do "Nope" end %>

<h2>Editing resources is not allowed.</h2>


<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<% content_for :title do "Resources" end %>

<h2>Listing resources</h2>

<table>
  <tr>
    <th>Url</th>
    <th>Request</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.url %></td>
    <td><%= resource.request_id %></td>
    <td><%= resource.user_id %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<% content_for :title do "New resource" end %>

<h2>New resource for request</h2>
<p>
  <b>Request requirements:</b>
  <%= @request.requirements %>
</p>

<p>
  <b>Request posted by:</b>
  <%= user @request %>
</p>


<%= form_for(@resource, :url => user_request_resources_path(@user, @request)) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p>
  <b>Url:</b>
  <%= @resource.url %>
</p>

<p>
  <b>For request:</b>
  <%= @resource.request_id %>
</p>

<p>
  <b>Provided by user:</b>
  <%= user @resource %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/resources/update.html.erb
<% content_for :title do "Nope" end %>

<h2>Updating resources is not allowed.</h2>


<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>